# defaults
language: node_js
node_js: "11"
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
cache:
  npm: true
  cargo: true
  bundler: true
  directories:
    - native/target
    - examples/ava/node_modules
    - examples/e2e/node_modules
    - examples/graphql/node_modules
    - examples/jest/node_modules
    - examples/karma/node_modules
    - examples/messages/node_modules
    - examples/mocha/node_modules
    - examples/serverless/node_modules
    - examples/typescript/node_modules
    - examples/v3/e2e/node_modules
    - examples/v3/todo-consumer/node_modules
env:
  global:
    # travis encrypt NPM_KEY=<key>
    - secure: "dadftjIY7w+KRucMDOqflXYTvWI1WYvtLtvGnbJuoFrgviax5zhwI7rSi6PTvW7mqV05FtqfVVb8Mgkwp1GNhv9byzuPCKnX6zN/tnl3mC++ivMA3BI7KhNp6VinzVeHWN+9BSYAQs1RQbslIK6IJ3oQJ9azp1MnxMQ1s0w5hqo0ojPWRJsm/IN57/pSiR4U0yyvONdwVg7Q8RQmyMZtovA2QzrR3ij6IxBwiJ7RQXsWIYkPL1SzaIqNNhMOdXK3m1iCESmtNc1BG9oEoaZc0ZzowT/O5VVPWe+bUfdSaAHjkTauaMCU2OAk6J89yd7pSCT5fe1YYYPgTIZiPkG0wQH8k7dKqqeaxBo+tN7uCfkYlTMNZmjv+qVBafoP8wBV97g3UugDqqIXaFknTUDnSNaigcJjFRWhCHBtltR+hzF6pCl3H1o1dDnmJWrgEb01qJ0lZonmaK/anZGNpUWE6qndOKBwnd0XiR1LnvzL/7tdflNb4DPy+lWdDEj4HWZR3lFA009m651qHBN+117ousZFXJ1866JywkAM2GrEWD4umzKknXDhulMG/Q32DS01BgW1pMenzQkH5WE+O0T3W/8BPw0Ev//bqZIg0gDckppUexHZ+pMhAFMaJfCzYVhrA0fhwLb+1EW7VDEcQIc0QHGXOb3Vclja7qB4yDuAJxk="
    # travis encrypt COVERALLS_REPO_TOKEN=<key>
    - secure: "lwfPOQAlWpM7PLddQ2BxE+MAgJgY7jooPZ8e1IBy9pja5KrFxHPjaoZVnqU8Xs6FgrvZPkUh8nK+FzHOAyczpbQP/atBLDDNkH87yGYpR+bRH6BhYusG0haY+14+d/7Dy2Jo+lAAk2q4ClXksmJ8mR4czxuv5/KzVR8SXvi4d/9mPv13Oc4es2zJ1EpZnVM1+knQQFQnbtAn64l5pfd7NNmwT79h+vgixl+E/SQTRA4xr/b4F4606X4CUKMNvHq4Y5AsJfzvZE3uPVQ9adV2issByOLsVuJbhqjp06m8zXlbilAhsSdDVCTQUVs7NeyyY0/BuCNMFpFrYsR7cpAZw4UneCK0+rqtblo60WNS3SzG+V7sXN4sk67CDw5qlnlA5c37xm8aEkUw9rQinhgEPK9DCnjg+O1Q2qb2xtP2+ImvIkaaHLe4mcNoq9mXWNpyUW2n3gRTXOvifTrIWHpS79MdNaGHhQiwVZtPnd5Triclzi68F6U5tLewf/Sb/9G2R2nDpm+ggpmfwZp0/WEn89vlWxEDvIZOy8vk03T/XUqEq3PifxCdsxiGBzVgaBUawPiAOcKab2NRlZfbY4TRG1ppryUlLydTYSCcRnjs6rEBgO7VOp1MoWGKH8SP4eEcp+s1N3pTXGAxGeJOKcOxu0M+Wk9pv61xpUCBwpaSh8Y="
    #- LOG_LEVEL=debug

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0; fi
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - export PATH="$PATH:$HOME/.cargo/bin"
  - source "$HOME/.cargo/env"
  - rustc --version
  - cargo --version
before_deploy:
  - npm run dist
  - npm run deploy:prepare

# these are executed in order.  each must pass for the next to be run
stages:
  - test # all tests
  - name: deploy
    if: (tag is present) AND (type = push)

jobs:
  include:
    - &test
      script: ./scripts/build.sh
      node_js: "11"
