# defaults
language: node_js
node_js: "12"
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
cache:
  - npm
  - cargo
env:
  global:
    # travis encrypt NPM_KEY=<key>
    - secure: "dadftjIY7w+KRucMDOqflXYTvWI1WYvtLtvGnbJuoFrgviax5zhwI7rSi6PTvW7mqV05FtqfVVb8Mgkwp1GNhv9byzuPCKnX6zN/tnl3mC++ivMA3BI7KhNp6VinzVeHWN+9BSYAQs1RQbslIK6IJ3oQJ9azp1MnxMQ1s0w5hqo0ojPWRJsm/IN57/pSiR4U0yyvONdwVg7Q8RQmyMZtovA2QzrR3ij6IxBwiJ7RQXsWIYkPL1SzaIqNNhMOdXK3m1iCESmtNc1BG9oEoaZc0ZzowT/O5VVPWe+bUfdSaAHjkTauaMCU2OAk6J89yd7pSCT5fe1YYYPgTIZiPkG0wQH8k7dKqqeaxBo+tN7uCfkYlTMNZmjv+qVBafoP8wBV97g3UugDqqIXaFknTUDnSNaigcJjFRWhCHBtltR+hzF6pCl3H1o1dDnmJWrgEb01qJ0lZonmaK/anZGNpUWE6qndOKBwnd0XiR1LnvzL/7tdflNb4DPy+lWdDEj4HWZR3lFA009m651qHBN+117ousZFXJ1866JywkAM2GrEWD4umzKknXDhulMG/Q32DS01BgW1pMenzQkH5WE+O0T3W/8BPw0Ev//bqZIg0gDckppUexHZ+pMhAFMaJfCzYVhrA0fhwLb+1EW7VDEcQIc0QHGXOb3Vclja7qB4yDuAJxk="
    # travis encrypt COVERALLS_TOKEN=<key>
    - secure: oiYYhYwSCq2kkdpq5Zb4Sx/6TSIl8sOP+nT0BRy1q7tY2oOXR6y+SxmJ6ayukJSMxnhqxKtTG36DJFml5RJFyKpGipr4p10npPYmSqz5L6H/wpAqfC8jeyWdQXGkytYoctfzW5vuQsF03Ub7Gn/JkAO6DOrk6uqYLiqgQuCqt9TYSv6VeO5BOYDPtlvlAWzaXWbip2zRCyI6lS62DtrGTq8z0OO4+tZgro5q6y84Y2UiAOfTIAOb+RHrPePccYD+5L1ptGB/eN7d6ClC2SlKoxrygqjIMNrgLzzSPSInIUQEPVotMsuQTWf3r5K3gKkOQnYQ2HPg9v+FAIBuDXOyQI78tFIBQgECpuVP/ywY4gI7SQoG/5UdN0Eaig9LvXshFwWZw9ABNOhP85lFiOMCBlidpJ+otu4ZUVFjdZsU+vRxVTn3nlHtcr7suCFZnhcEgI1wxj7uIl9w8Fx8xn1fqkXFBgfCpA78pzTuks92uOgDV/rFSqSskDqvJXv5fBVamuqWAIRmZq9lCyYl4F7rOPA7TWLvwmQ1G7ECs9OLRPZim1iSiFKKX07ecJD8RVw8akXd15lubDDDQbWDgP+3MX0TarVHjl58eJSjzinKqt8fpn4f+P89mLJRHCnCxaWqAlO90L+aG9LKrOmsMoQii9ve39iyNv0UVehfHsOHwIY=
    #- LOG_LEVEL=debug

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0; fi
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - export PATH="$PATH:$HOME/.cargo/bin"
  - source "$HOME/.cargo/env"
  - rustc --version
  - cargo --version
before_deploy:
  - npm run dist
  - npm run deploy:prepare

# these are executed in order.  each must pass for the next to be run
stages:
  - test # all tests
  - name: deploy
    if: (tag is present) AND (type = push)

jobs:
  include:
    - &test
      script: ./scripts/build.sh
      node_js: "10"

    - <<: *test
      node_js: "12"

    - <<: *test
      node_js: "14"

    - stage: 🚀 publish to npm 🚀
      node_js: "12"
      if: tag IS present
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./scripts/publish.sh
          on:
            tags: true
        - provider: releases
          api_key:
            secure: FmoLJnO8GNxyztR2P433ZCumYPrxiZdBCfVhmhTGYlXhOfVaAECm0gUVPLZuBQRUaqsef5ekg+OSIA5xbrnNoOQ9qlmnF2n+5yiwqG6o35XLA4L6lB5pL+x8xoAAgpaj9dTD184HKGdub3heQStTPRd2ll3nNRwxhfyIyBaMX3elDTH3mkV2QxNhG1RTgJe322PQrwoU2sWkghTWNr4t+h/G+oYu364xwZuxFX1hrFpAW+IEmbDSuhmCe24lMU96ntIiciRU3eBYR7s3KlktOFgMORXMRw3H/qaGmx7rKtpJ892XGRuVbw+tPB3A1jbFvOwJwzpnsWG5REu3PkZ6oiWpnX+5riN3jPyvFpWd+LLfH1KdZeBnF/anEfl+mSPdrDROOWotV3Xt5zOiEwx2j4BRbDNfa6wXzX0zK31AMf0IFmw7KZJkzcyWjNRluxTn3r2bbjNoi+gBojQuX27R3AQz5G0E0yZUk5ujmcd+85WOgNh/zVwsZLHYVQxDyULkbDTCDAulBsJLyxUFRs0JixyHCvA6srrUdpcO0NdyDfvULk9e/g/c9aD56Rk4xT4/Xa7K1fAHLjLkV6CA4H9Of96Zl2BK8r6LAlw382hO7FaZH+A3YShObEeTiZsDbfSQrFl5x8aimvc9oeYopvvQ+EdZxHvvwxHQIp/MWOybdJ4=
          file: pactjs.tar.gz
          skip_cleanup: true
          on:
            tags: true
