# build version format
version: "{build}"

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# Test against these versions of Node
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "13"

platform:
  - x64

matrix:
  fast_finish: true
skip_tags: true
skip_branch_with_pr: true

# Setup Node environment
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - appveyor-retry appveyor DownloadFile "https://static.rust-lang.org/rustup/dist/%TARGET%/rustup-init.exe" -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\msys64\mingw64\bin;C:\Program Files\LLVM\bin
  - rustup show
  - rustc -V
  - cargo -V
  - gcc --version
  - npm install

# Run custom build script instead of MSBuild
build_script:
  - powershell .\scripts\build.ps1
