name: Build, test, test all examples

on:
  push:
  pull_request:
    branches: [master, feat/v3.0.0]

jobs:
  build-and-test-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: scripts/ci/build-and-test.sh
        env:
          NODE_VERSION: ${{ matrix.node-version }}
